defaults:
  - base_config
  - bot: default
  - database: default
  - logging: default
  - regulation: default
  - scheduler: default
  - schedule_chart: default
  - ram_input: default
  - list_grids: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

interface: reply_keyboard  # "legacy" (classic inline menu) or "reply_keyboard"

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
