defaults:
  - base_config
  - web: default
  - database: default
  - logging: default
  - regulation: default
  - scheduler: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

timezone: UTC

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
